version: '2'
services:
  postgres:
    image: "postgres:11.8"
    container_name: postgres
    restart: always
    volumes:
      - '../.././db:/var/lib/postgresql/data'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cook-book
    command: postgres -c 'datestyle=iso,dmy'
  php:
    image: "php:7.3-fpm"
    container_name: php
    restart: always
    working_dir: /opt/project
    volumes:
      - '../.././project:/opt/project'
      - './php.ini:/etc/php/7.3/fpm/php.ini:ro'
    depends_on:
      - postgres
    links:
      - postgres
  nginx:
    image: "nginx:1.19.1"
    container_name: nginx
    restart: always
    volumes:
      - '../.././project:/opt/project:ro'
      - '../.././logs:/opt/logs'
      - './nginx.conf:/etc/nginx/conf.d/default.template:ro'
    environment:
      SERVER_NAME: 'baseapp.local'
    depends_on:
      - php
    links:
      - php
    ports:
      - 80:80
      - 443:443
  node:
    image: "node:14.7"
    container_name: node
